version: '3.11.4'

networks:
  my-network:
    driver: bridge

volumes:
  shared-static:
    driver: local
  db-data:
  media_volume:

services:
  server:
    build:
      context: .
    privileged: true
    environment:
      - TZ=Europe/Moscow
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/app
      - shared-static:/app/static  # Используем shared-static для статических файлов
      - media_volume:/app/media
    networks:
      - my-network
    env_file:
      - ./ShareBook/.env

  nginx:
    image: nginx:1.25.4
    environment:
      - TZ=Europe/Moscow
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - shared-static:/usr/share/nginx/html/static  # Используем shared-static для статических файлов
      - media_volume:/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - my-network
    env_file:
      - ./ShareBook/.env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network
    env_file:
      - ./ShareBook/.env

  celery:
    build:
      context: .
    command: celery -A ShareBook worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - my-network
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - ./ShareBook/.env

  react:
    build:
      context: ../sharebooks-design
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Moscow
      - NODE_ENV=production
    volumes:
      - ../sharebooks-design:/app
      - shared-static:/usr/share/nginx/html
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - my-network
    env_file:
      - ../sharebooks-design/.env

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - TZ=${TIME_ZONE}
      - POSTGRES_DB=ShareBook
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network
    env_file:
      - ./ShareBook/.env
