# Generated by Django 4.2.1 on 2024-04-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.URLField(max_length=500),
        ),
    ]
