# Generated by Django 4.2.1 on 2024-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_book_age_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
