# Generated by Django 4.2.1 on 2024-05-01 13:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_book_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myBooks', '0003_booktransfer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('book', 'user')},
        ),
    ]
