# Generated by Django 4.2.1 on 2024-05-08 13:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0006_alter_book_age_restriction'),
        ('myBooks', '0004_alter_userbook_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 8, 13, 24, 18, 689087, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WishBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'user')},
            },
        ),
    ]
